language: r
dist: trusty
sudo: false

branches:
  only:
    - source

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"

script:
  - "Rscript -e 'blogdown::build_site()'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: hingeloss.com
  on:
    branch: source
  local_dir: public
  target_branch: master
