baseurl = "/"
languageCode = "en-us"
title = "Chris Hua"
theme = "hugo-ivy"
googleAnalytics = "UA-107746756-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    permalink = "/"
    weight = 1
[[menu.main]]
    name = "About"
    permalink = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    permalink = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    permalink = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    permalink = "/index.xml"

[params]
    description = "Data Scientist."
    footer = "&copy; Chris Hua 2017 | [Github](https://github.com/stillmatic) | [Twitter](https://twitter.com/hingeloss)"
    favicon = "/favicon.png"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
